{{- if and .Values.auth.jwtSecret .Values.auth.oidc.clientSecret (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "externaldns-web-ui.fullname" . }}-auth
  labels:
    {{- include "externaldns-web-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.auth.oidc.clientSecret | quote }}
{{- end }}
